from datetime import datetime
import html

# PATTERN 4: BUILDER
class OCRReport:
    """
    @brief Складний об'єкт звіту (Product у патерні Builder).
    
    Містить результати розпізнавання, метадані та форматування.
    """
    def __init__(self):
        self.header = ""
        self.content = ""
        self.metadata = ""
        self.footer = ""

    def __str__(self):
        """
        @brief Форматує звіт для відправки у Telegram (HTML/Markdown).
        @return Сформатований рядок звіту.
        """
        return f"{self.header}\n\n{self.content}\n\n{self.metadata}\n{self.footer}"

class ReportBuilder:
    """
    @brief Клас-будівельник для покрокового створення об'єкта OCRReport (Патерн Builder).
    
    Дозволяє створювати різні представлення складного об'єкта 
    та уникає "телескопічних" конструкторів з великою кількістю параметрів.
    """
    def __init__(self):
        self.reset()

    def reset(self):
        """@brief Скидає поточний звіт до порожнього стану."""
        self._report = OCRReport()
        return self

    def set_header(self, title: str):
        """@brief Встановлює заголовок звіту."""
        self._report.header = f"📑 **{title}**"
        return self

    def set_content(self, text: str):
        """
        @brief Встановлює основний текст розпізнавання.
        
        Автоматично екранує HTML теги, щоб уникнути помилок форматування в Telegram.
        """
        safe_text = html.escape(text[:3500]) if text else "No text found."
        self._report.content = f"<pre>{safe_text}</pre>"
        return self

    def set_metadata(self, author_name: str, doc_type: str):
        """@brief Додає метадані (автор, тип документа, час обробки)."""
        current_time = datetime.now().strftime("%Y-%m-%d %H:%M")
        self._report.metadata = f"👤 *Author:* {author_name} | 🏷 *Type:* {doc_type}\n🕒 *Processed at:* {current_time}"
        return self

    def set_footer(self):
        """@brief Встановлює стандартизований підвал звіту."""
        self._report.footer = "🤖 _Generated by SmartHub Engine_"
        return self

    def get_result(self) -> OCRReport:
        """
        @brief Повертає готовий звіт та скидає будівельника.
        @return Об'єкт OCRReport.
        """
        report = self._report
        self.reset()
        return report